[theme]
primaryColor = "#31333F"  # Color de texto oscuro
backgroundColor = "#000000"  # Fondo negro
secondaryBackgroundColor = "#1A1A1A"  # Fondo secundario oscuro
textColor = "#FFFFFF"  # Texto en blanco
font = "sans serif"
